[package]
name = "indexed-merkle-tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto-hash = "0.3.4"
num = "0.4.0"
serde = { version = "1.0.151", features = ["derive"] }
thiserror = "1.0.50"
serde_json = "1.0.79"
async-redis-session = "0.2.2"