[package]
name = "indexed-merkle-tree"
version = "0.3.0"
edition = "2021"
authors = ["Ryan Ford <ryan@deltadevs.xyz>", "Sebastian Pusch <sebastian@deltadevs.xyz>"]
description = "This crate provides an implementation of Indexed Merkle Trees, a version of Merkle trees that supports both membership and non-membership proofs."
homepage = "https://github.com/deltadevsde/indexed-merkle-tree"
repository = "https://github.com/deltadevsde/indexed-merkle-tree"
license = "MIT"
keywords = ["crypto", "merkle-tree", "membership", "non-membership"]
readme = "README.md"

[dependencies]
serde = { version = "1.0.151", features = ["derive", "rc"] }
no-std-thiserror = "0.1.0"
serde_json = { version = "1.0.117", default-features = false, features = ["alloc"] }
cargo-audit = "0.20.0"
sha2 = "0.10.8"
hex = {version = "0.4.3", default-features = false }
