name: Rust CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        rust:
          - version: stable
            profile: minimal
          - version: beta
            profile: default
          - version: nightly
            profile: default

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        run: |
          rustup toolchain install ${{ matrix.rust.version }} --profile ${{ matrix.rust.profile }}
          rustup default ${{ matrix.rust.version }}

      - name: Install protoc
        run: sudo apt-get install protobuf-compiler

      - name: Cache cargo build
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}-cargo-${{ matrix.rust.version }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Install dependencies
        run: cargo fetch

      - name: Add clippy component if not stable
        if: matrix.rust.version != 'stable'
        run: rustup component add clippy

      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Build project
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose 
        
      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Run cargo audit
        run: cargo audit
